"""equipo_modify(fecha_creacion)

Revision ID: 32e1aeb9ae85
Revises: 8c18207e12d1
Create Date: 2026-06-09 19:52:51.982788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '32e1aeb9ae85'
down_revision: Union[str, None] = '8c18207e12d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipos', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipos', 'fecha_creacion')
    # ### end Alembic commands ###