"""add_tickets

Revision ID: 3716fd4e4707
Revises: 1f83bb9cfd2f
Create Date: 2026-06-03 21:09:48.569832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3716fd4e4707'
down_revision: Union[str, None] = '1f83bb9cfd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=255), nullable=False),
    sa.Column('urgencia', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('tecnico_id', sa.UUID(), nullable=False),
    sa.Column('equipo_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###