"""ticket_modify(direccion)

Revision ID: 8c18207e12d1
Revises: 9dbd57e0afb4
Create Date: 2026-06-08 21:19:18.201553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8c18207e12d1'
down_revision: Union[str, None] = '9dbd57e0afb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('direccion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'direccion')
    # ### end Alembic commands ###