"""ticket_modify(tecnico_id optional)

Revision ID: 9dbd57e0afb4
Revises: 3716fd4e4707
Create Date: 2026-06-08 19:19:14.684606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9dbd57e0afb4'
down_revision: Union[str, None] = '3716fd4e4707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'tecnico_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'tecnico_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###